### ISSUE TITLE
The Load Schematics button doesnt work on 1.21.6

### ISSUE THREAD

**Issue by ym12344** [maruohon/litematica#1009]
### Provide at least the following information
* **Minecraft version** - 1.21.6
* **Mod version and malilib version** - Litematica 0.23.3    Malilib 0.25.4
Every button works except for the load schematics button. When i press it it just goes into saving world then quits the game. I dont think i can link my .minecraft file here. Let me know if you need anymore info. I might be a little bit busy

**Comment by maruohon** [comment]
We at least need the crash log, without it it's impossible to know or do anything about the cause.

**Comment by ym12344** [comment]
Where can I find the crash log? Thanks for quick reply

**Comment by maruohon** [comment]
It should be in the `crash-reports` directory inside that game/minecraft directory. Or if there isn't one there, then the `logs/latest.log` file is usually fine too. Just check that you get it from the correct game instance, and that the modified timestamp in the log matches to when your game crashed. (I've seen people sometimes send the wrong logs from months ago.)

**Comment by ym12344** [comment]
[crash-2025-08-07_19.14.48-client.txt](https://github.com/user-attachments/files/21663838/crash-2025-08-07_19.14.48-client.txt)

**Comment by ym12344** [comment]
I hope this works

**Comment by maruohon** [comment]
You are missing a mod that *something* tries to use, but I can't see what tries to access it.

```
java.lang.NoClassDefFoundError: io/wispforest/owo/ui/base/BaseOwoScreen
```

I assume this is from the Owolib or Uwulib mod or something? Is this related to you using the Wurst client in some way?

**Comment by ym12344** [comment]
I'm sure I didn't download owolib should I try? I am also using wurst

**Comment by maruohon** [comment]
Well I mean *something* tries to load that one class from it. But it's strange if nothing defines a dependency to that mod... So idk what exactly is going on.

You could also try removing all mods except Litematica and malilib, try if it works then, and then add back the mods in small groups (or use bisecting and remove half of the mods at a time, halving the affected group each time to find the one mod that needs it). But idk if there is a reason to find out which mod needs it, if you need the mod that needs the lib then you need the lib anyway.

**Comment by ym12344** [comment]
I'll try downloading owolib

**Comment by ym12344** [comment]
Since there's no need to remove any mods if it works

**Comment by ym12344** [comment]
Now it works tq very much
