### ISSUE TITLE
 Error! Game could not be started

### ISSUE THREAD

**Issue by Dejaanx3** [maruohon/litematica#50]
Hello 

I watched a youtube video and downloaded all the stuff and now I want to start fabric and it says 
Error! Game could not be started.

What should I do?

(Version: 1.14.4)

**Comment by vacla** [comment]
can you provide the crashlog in [pastebin.com](pastebin.com)

**Comment by SunSerega** [comment]
You can also upload files here, just drag and drop it into the message.

**Comment by Dejaanx3** [comment]
https://www.directupload.net/file/d/5532/a3mwad73_png.htm

i can't find any crashlogs

**Comment by SunSerega** [comment]
They are in:

`.minecraft\crash-reports`
or
`.minecraft\home\1.14\crash-reports`
or
`.minecraft\home\1.14.4\crash-reports`

**Comment by Dejaanx3** [comment]
that is my last crash report

https://www.directupload.net/file/d/5534/v3hgpxcu_png.htm

**Comment by SunSerega** [comment]
Yes, now drag and drop it into the answer here. Screenshot only shows existence of that crash-report. And you need to send it's contents, preferably in text form.

**Comment by Dejaanx3** [comment]
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 03.06.19 18:34
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property bmh{name=part, clazz=class blz, values=[head, foot]} as it does not exist in Block{minecraft:chest}
	at bla.c(SourceFile:95)
	at cvz.a(SourceFile:40)
	at cvz.a(SourceFile:17)
	at cwa.a(SourceFile:148)
	at cwa.a(SourceFile:128)
	at fi.dy.masa.litematica.render.schematic.WorldRendererSchematic.a(WorldRendererSchematic.java:808)
	at fi.dy.masa.litematica.render.LitematicaRenderer.renderWorld(LitematicaRenderer.java:164)
	at fi.dy.masa.litematica.render.LitematicaRenderer.renderSchematicWorld(LitematicaRenderer.java:69)
	at fi.dy.masa.litematica.event.RenderHandler.onRenderWorldLast(RenderHandler.java:25)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderWorldLast(RenderEventHandler.java:61)
	at cty.handler$onRenderWorldLast$zcj000(SourceFile:1496)
	at cty.b(SourceFile:1058)
	at cty.a(SourceFile:875)
	at cty.a(SourceFile:749)
	at cft.c(SourceFile:850)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at bla.c(SourceFile:95)
	at cvz.a(SourceFile:40)
	at cvz.a(SourceFile:17)

-- Block Entity Details --
Details:
	Name: minecraft:bed // bjh
	Block: Block{minecraft:chest}[facing=east,type=single,waterlogged=false]
	Block location: World: (9340,79,-4636), Chunk: (at 12,4,4 in 583,-290; contains blocks 9328,0,-4640 to 9343,255,-4625), Region: (18,-10; contains chunks 576,-320 to 607,-289, blocks 9216,0,-5120 to 9727,255,-4609)
	Block: Block{minecraft:chest}[facing=east,type=single,waterlogged=false]
	Block location: World: (9340,79,-4636), Chunk: (at 12,4,4 in 583,-290; contains blocks 9328,0,-4640 to 9343,255,-4625), Region: (18,-10; contains chunks 576,-320 to 607,-289, blocks 9216,0,-5120 to 9727,255,-4609)
Stacktrace:
	at cwa.a(SourceFile:148)
	at cwa.a(SourceFile:128)
	at fi.dy.masa.litematica.render.schematic.WorldRendererSchematic.a(WorldRendererSchematic.java:808)
	at fi.dy.masa.litematica.render.LitematicaRenderer.renderWorld(LitematicaRenderer.java:164)
	at fi.dy.masa.litematica.render.LitematicaRenderer.renderSchematicWorld(LitematicaRenderer.java:69)
	at fi.dy.masa.litematica.event.RenderHandler.onRenderWorldLast(RenderHandler.java:25)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderWorldLast(RenderEventHandler.java:61)
	at cty.handler$onRenderWorldLast$zcj000(SourceFile:1496)
	at cty.b(SourceFile:1058)
	at cty.a(SourceFile:875)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [ctj['Dejaanx3'/4097394, l='MpServer', x=9304.93, y=78.80, z=-4597.18]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (4171,68,6201), Chunk: (at 11,4,9 in 260,387; contains blocks 4160,0,6192 to 4175,255,6207), Region: (8,12; contains chunks 256,384 to 287,415, blocks 4096,0,6144 to 4607,255,6655)
	Level time: 104453 game time, 295319469 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 14 total; [ctj['Dejaanx3'/4097394, l='MpServer', x=9304.93, y=78.80, z=-4597.18], alz['Armour Stand'/4097406, l='MpServer', x=9353.50, y=65.00, z=-4588.50], alz['Armour Stand'/4097404, l='MpServer', x=9353.50, y=65.00, z=-4598.50], ame['Painting'/4097400, l='MpServer', x=9335.03, y=69.00, z=-4606.00], alz['Armour Stand'/4097402, l='MpServer', x=9342.50, y=65.00, z=-4608.50], alz['Armour Stand'/4097403, l='MpServer', x=9337.50, y=65.00, z=-4588.50], ame['Painting'/4097400, l='MpServer', x=9335.03, y=69.00, z=-4606.00], alz['Armour Stand'/4097401, l='MpServer', x=9337.50, y=65.00, z=-4608.50], alz['Armour Stand'/4097398, l='MpServer', x=9337.50, y=65.00, z=-4602.50], alz['Armour Stand'/4097399, l='MpServer', x=9337.50, y=65.00, z=-4598.50], alz['Armour Stand'/4097397, l='MpServer', x=9342.50, y=65.00, z=-4602.50], alz['Armour Stand'/4099499, l='MpServer', x=9360.35, y=68.01, z=-4572.33], alz['Armour Stand'/4097408, l='MpServer', x=9359.63, y=68.35, z=-4572.53], alz['Armour Stand'/4097409, l='MpServer', x=9358.85, y=68.90, z=-4572.46]]
	Retry entities: 0 total; []
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at crg.a(SourceFile:418)
	at cft.b(SourceFile:1815)
	at cft.a(SourceFile:403)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 991034624 bytes (945 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2-rift-1.0.4-SNAPSHOT
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTX 560 Ti/PCI/SSE2 GL version 4.2.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'rift'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, litematica, malilib
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz

**Comment by maruohon** [comment]
You said you are on 1.14.4, but that crash report is from the beginning of June from Minecraft 1.13.2 (and seems to be for the rendering crash that was fixed in the June 11th build).

**Comment by Dejaanx3** [comment]
I know but I should send it in?

**Comment by vacla** [comment]
put the crash report here that you had with fabric

**Comment by Vekkish** [comment]
Yeah........ I'm having the same problem but there is no crash report to be found looked in C:\Users\name\AppData\Roaming\.minecraft\crash-reports not finding any crash report for this instance just crashes with no report when adding:  litematica-fabric-1.14.3-0.0.0-dev.20190630.024955 and I'm using Minecraft version 1.14.2

**Comment by vacla** [comment]
@Vekkish which Malilib version and can you give the latest.log also ?

**Comment by Vekkish** [comment]
Im useing Malilib-fabric 1.14.2-0.9.6

latest.log just says

[20:39:46] [main/INFO]: Loading for game Minecraft 1.14.2

**Comment by vacla** [comment]
@Vekkish download latest malilib from https://masa.dy.fi/tmp/minecraft/mods/client_mods/

**Comment by Vekkish** [comment]
Yeah just did that same thing even took out the litematic mod and same occurs with the malilib-fabric 1.14.2-0.9.6 without litematic starts up no problem

**Comment by vacla** [comment]
@Vekkish you tried malilib 0.10.0-dev.20 ?

**Comment by Vekkish** [comment]
Correct

**Comment by maruohon** [comment]
Did you update all the mods to the latest version from that page (and for the correct Minecraft version too)? You can't mix older and newer builds of my mods due to their dependency on malilib things. Can you screenshot your mods folder?

**Comment by Vekkish** [comment]
![mod folder](https://user-images.githubusercontent.com/54047204/62908027-e8efd100-bd43-11e9-9bef-2323f33d28fb.png)

**Comment by Vekkish** [comment]
i moved them all for a moment to try just the fabric mods and litematic

**Comment by vacla** [comment]
try update minihud @Vekkish

**Comment by maruohon** [comment]
Well that's still the old 0.9.x malilib, it won't work with Litematica. Get the 0.10.0-dev.20 version. And then update MiniHUD to the latest build. And it looks like you need to try if the 1.14.3 or 1.14.4 Tweakeroo works on 1.14.2, as that old Tweakeroo was made for malilib 0.9.x and won't work with the malilib 0.10.0 version.

**Comment by Vekkish** [comment]
working with 1.14.2 look like i do have the latest minihud

**Comment by Vekkish** [comment]
getting a crash report finally tho


---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/12/19 9:10 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: java.lang.NoSuchMethodError: fi.dy.masa.malilib.event.InitializationHandler.getInstance()Lfi/dy/masa/malilib/event/InitializationHandler;
		at fi.dy.masa.minihud.MiniHUD.onInitialize(MiniHUD.java:28)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointClient$$Lambda$1413/1539280298.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.lambda$logErrors$0(EntrypointUtils.java:38)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils$$Lambda$1414/1537685787.accept(Unknown Source)
		at java.util.ArrayList.forEach(ArrayList.java:1249)
		at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:36)
		... 11 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.hooks.EntrypointUtils.logErrors(EntrypointUtils.java:45)
	at net.fabricmc.loader.entrypoint.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3871552432 bytes (3692 MB) / 4294967296 bytes (4096 MB) up to 17179869184 bytes (16384 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		blue_endless_jankson: jankson 1.1.0
		cloth: Cloth Events 0.3.1+build.23
		cloth-config2: Cloth Config v2 0.1.0
		fabric: Fabric API 0.3.0+build.176
		fabric-api-base: fabric-api-base 0.1.0+59147463
		fabric-commands-v0: fabric-commands-v0 0.1.1+25fd0c52
		fabric-containers-v0: fabric-containers-v0 0.1.2+25fd0c52
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+45e1a1c8
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+59147463
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+59147463
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+59147463
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+59147463
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.0+59147463
		fabric-language-kotlin: Fabric Language Kotlin 1.3.31+build.4
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+59147463
		fabric-models-v0: fabric-models-v0 0.1.0+59147463
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+25fd0c52
		fabric-networking-v0: fabric-networking-v0 0.1.2+200eb5c2
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+9fe2f882
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.1+4d26f9ba
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.0+02a46d5b
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.4+9ff0718a
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+02a46d5b
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c2
		fabric-rendering-v0: fabric-rendering-v0 0.1.0+59147463
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+59147463
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.0+59147463
		fabric-textures-v0: fabric-textures-v0 0.1.4+792c1c35
		fabricloader: Fabric Loader 0.4.8+build.155
		litematica: Litematica 0.0.0-dev.20190624.221035
		malilib: MaLiLib 0.10.0-dev.20
		minihud: MiniHUD 0.19.0-dev.20190527.190919
		mm: Manningham Mills 1.6
		modmenu: Mod Menu 1.6.2-92
		net_fabricmc_stitch: stitch 0.1.2.49+
		optifabric: Optifabric 0.2.0
		org_jetbrains_annotations: annotations 16.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.2.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.2.1
		org_slf4j_slf4j-api: slf4j-api 1.7.26
		org_slf4j_slf4j-simple: slf4j-simple 1.7.26
		org_zeroturnaround_zt-zip: zt-zip 1.13
		roughlyenoughitems: Roughly Enough Items 2.9.5+build.131
	Launched Version: fabric-loader-0.4.8+build.155-1.14.2+build.7
	LWJGL: 3.2.1 build 12
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null

**Comment by maruohon** [comment]
`MiniHUD 0.19.0-dev.20190527.190919`

The latest for 1.14.2 seems to be `0.19.0-dev.20190624.221851`.

**Comment by vacla** [comment]
doesn't work with minihud

**Comment by Vekkish** [comment]
yep its up and working now after reading the report after I sent it i noticed the minihud and went to the page from earlier for the malilib file and got it loading fine now

thanks alot @maruohon and @vacla

**Comment by vacla** [comment]
@Dejaanx3 did you get it working?

**Comment by Dejaanx3** [comment]
no >.<

**Comment by maruohon** [comment]
Then screenshot your mods folder, and such that it's possible to see all the mod version numbers/filenames.

**Comment by vacla** [comment]
@Dejaanx3 any status on it?
