### ISSUE TITLE
schematic verifier isnt working in 0.26.12

### ISSUE THREAD

**Issue by ghatt-o** [maruohon/litematica#1137]
### Provide at least the following information
* **Minecraft version** - 1.21.11
* **Mod version and malilib version** - v0.26.12
  litematica-fabric-1.21.11-0.26.12.jar - malilib-fabric-1.21.11-0.27.16.jar 
* **A clear description of the issue** - the schematic verifier isn't working as it should as when i click start verification, this error pops up on the logs:
Caused by: java.lang.NoClassDefFoundError: fi/dy/masa/litematica/data/EntitiesDataStorage
	at knot//fi.dy.masa.litematica.schematic.verifier.SchematicVerifier.handler$ejh000$techutils$clearAdditionalData(SchematicVerifier.java:1322)
	at knot//fi.dy.masa.litematica.schematic.verifier.SchematicVerifier.clearData(SchematicVerifier.java)
	at knot//fi.dy.masa.litematica.schematic.verifier.SchematicVerifier.reset(SchematicVerifier.java:342)
	at knot//fi.dy.masa.litematica.schematic.verifier.SchematicVerifier.startVerification(SchematicVerifier.java:303)
	at knot//fi.dy.masa.litematica.gui.GuiSchematicVerifier$ButtonListener.actionPerformedWithButton(GuiSchematicVerifier.java:470)
	at knot//fi.dy.masa.malilib.gui.button.ButtonBase.onMouseClickedImpl(ButtonBase.java:87)
	at knot//fi.dy.masa.malilib.gui.widgets.WidgetBase.onMouseClicked(WidgetBase.java:96)
	at knot//fi.dy.masa.malilib.gui.GuiBase.onMouseClicked(GuiBase.java:332)
	at knot//fi.dy.masa.malilib.gui.GuiListBase.onMouseClicked(GuiListBase.java:94)
	at knot//fi.dy.masa.malilib.gui.GuiBase.method_25402(GuiBase.java:263)
	at knot//net.minecraft.class_312.mixinextras$bridge$method_25402$60(class_312.java)
	at knot//net.minecraft.class_312.wrapOperation$zcl000$architectury$wrapMouseClicked(class_312.java:2083)
	at knot//net.minecraft.class_312.mixinextras$bridge$wrapOperation$zcl000$architectury$wrapMouseClicked$63(class_312.java)
	at knot//net.minecraft.class_312.wrapOperation$did000$fabric-screen-api-v1$invokeMouseClickedEvents(class_312.java:2553)
	at knot//net.minecraft.class_312.method_1601(class_312.java:122)
	... 22 more
Caused by: java.lang.ClassNotFoundException: fi.dy.masa.litematica.data.EntitiesDataStorage
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:239)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 37 more

**Comment by maruohon** [comment]
I believe these are due to the Technical Utilities mod needing to be updated to some recent Litematica code changes. Check if there is a newer version of TU already available, if not ,then you may need to disable it for now when you need to use the verifier.
